<?php /** @var $block Hiperdino\Dinitos\Block\History; */ ?>

<?php
$showDinitosHistory = $block->isDinitosLinkEnabled();
$defaulPosition = 2;
$linkPosition = $block->getData('link_position') ?: $defaulPosition;
$linkText = $block->getDinitosHistoryTexts()['text_link_sidebar'];
?>

<?php if ($showDinitosHistory): ?>
    <li class="sidebar-item--wrapper flex-item order-<?= $linkPosition ?>">
        <a href="<?= $block->getUrl('dinitos_history') ?>" class="link-info item--container flex-container flex-row items-center">
            <div class="sidebar__item-info flex-item icon-dinitos-mobile">
                <i class="icon icon-dinitos"></i>
            </div>
            <div class="link--wrapper menu--link dropdown---info flex-item">
                <?= __($linkText) ?>
            </div>
        </a>
    </li>
<?php endif; ?>
